### ISSUE TITLE
Omit protocolApplied from profiles or make it optional

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#10]
The `protocolApplied` and details like `doseNumber` and `targetDisease` may not in general be known -- or if populated may be incorrect. But a receiving system can interpret the actual products and timing based on other data elements. I worry that packing in this kind of detail will

*  make it harder for some participants to fill out the required data, leading them to populate fields incorrectly to satisfy the `1..1` validator requirements, and
* lead to larger payload sizes

**Comment by jmandel** [comment]
Different perspective I heard recently re: `doseNumber`: Some verifiers might be happy enough seeing something labeled as `"doseNumber": 2`, even in the absence of other evidence of previous immunization -- so this is an argument for leaving it in. (That's pretty compelling; but I'd still omit `targetDisease`.)

**Comment by rickybloomfield** [comment]
I think the question about payload sizes is valid, but I worry in this case that the issuers would be leaving valuable information on the table.

For example, a user might receive two separate credentials for their 1st and 2nd doses. They might choose to only share the second, believing that sharing that one would be sufficient. I believe we should leave it up to the issue to determine if they are confident in the accuracy of these fields and I would suggest that while the field should be optional, we should encourage its use if the issuer has the data.

**Comment by Mturman3** [comment]
Making the ProtocolApplied elements 'must-support' with an intent that it be used by Verifiers puts Issuers that do not capture and/or do not support these elements in a tough spot.

**Comment by masnick** [comment]
Another piece of information supporting making this optional or removing entirely:

Per discussion at a session of the public health FHIR working group last week, `protocolApplied` is meant to represent the **provider's intent**, not the whether the vaccination actually qualifies as the nth dose in a series.

The [ImmunizationEvaluation](https://www.hl7.org/fhir/immunizationevaluation.html) resource is meant to interpret an Immunization in the context of the patient's history and the vaccination schedule. Presumably `ImmunizationEvaluation.doseNumber` and `ImmunizationEvaluation.seriesDoses` would be authoritative.

Based on this, I think our options are one or both of the following:

1. Use `Immunization` and make the dose/series elements optional and not MS given that "provider's intent" doesn't seem like a very strong signal for our use cases
2. Switch to or also allow for `ImmunizationEvaluation` resources as part of the bundle.

I favor just Option 1 as a starting point since the dose/series information isn't necessarily available in the EHR anyway, it's simpler, and it seems like we would want to leave the "evaluation" up to the party receiving the VC anyway. This would mean that separate `Immunization` resources would be required in the bundle for each dose of the COVID vaccine, rather than theoretically just including a single resource.

I'm open to Option 2 (profiling `ImmunizationEvaluation`) as well, but I think we should make sure there is a solid use case justification before adding it.

**Comment by nkarip** [comment]
1. Agree that all protocolApplied children should be optional, and I would be in favor of removing entirely. I can't imagine any immunization forecasting decision support service would rely on "provider's intent" as Max stated.
2. For communicating whether series is complete or not, it seems ImmunizationRecommendation is the existing resource to use and I believe it doesn't need profiling. It may work as-is. ImmunizationEvaluation seems to be focused on a single Immunization instance and not making a decision on a series.

**Comment by masnick** [comment]
> Agree that all protocolApplied children should be optional, and I would be in favor of removing entirely. I can't imagine any immunization forecasting decision support service would rely on "provider's intent" as Max stated.

Right now our profiling approach is to use MS to indicate the fields that should be populated, and "soft remove" the non-MS, non-required by instructing implementers to only populate the MS fields.

I don't think we should set `0..0` cardinality to "hard remove" an element unless the element has no valid interpretation in our use case and a resource that includes it would be confusing or uninterpretable.

In this case, I could see an argument for that we **should** set the cardinality to `0..0` as receivers may not be aware of the "provider intent" interpretation. I personally would feel more comfortable if receivers figured out the series number based on the timestamps of two Immunization resources, but I realize there are payload constraints and the patient may not have both doses in the bundle for some reason.

> For communicating whether series is complete or not, it seems ImmunizationRecommendation is the existing resource to use and I believe it doesn't need profiling. It may work as-is. ImmunizationEvaluation seems to be focused on a single Immunization instance and not making a decision on a series.

I think we could use either ImmunizationSeries or ImmunizationRecommendation to provide an authoritative number of doses received for a given vaccine. If anyone thinks this is worth doing, can you please provide some use case background that we can integrate into the IG to justify?

**Comment by Mturman3** [comment]
The ultimate audience for these resources is a Verifier, right? My thinking is that if an element is inconsistently valued from Issuer to Issuer can't be used in validation. And given the immediate use case, where the number of doses has some importance, it seems that inclusion of this element is meant to inform the validity of the credential, regardless of whether implementers are required to support it.

**Comment by jmandel** [comment]
Agreed 100% with the perspective and rationale in https://github.com/dvci/vaccine-credential-ig/issues/10#issuecomment-772086970 -- thanks @masnick

**Comment by rickybloomfield** [comment]
Also agree with the logic presented by @masnick above.

**Comment by Mturman3** [comment]
Agree with 0..0 cardinality on protocolApplied. Timestamps in occurrence should be a suitable work-around for Verifers interested in dose number/sequence.
