### ISSUE TITLE
Simplify "subPotent" documentation

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#18]
FHIR spec says: 

> Indication if a dose is considered to be subpotent. By default, a dose should be considered to be potent.

I'd suggest simplifying our profile here to keep `isSubpotent` as mustSupport, but document that implementers should only populate this in resources if the value is `true`. I'd leave out any requirements for `subpotentReason` unless we determine this is well supported by existing data capture systems and relevant for interpretation (e.g., execution of risk evaluation rules).

**Comment by masnick** [comment]
@torresdrew in #23:

> isSubpotent and subpotentReason fields are not supported as an issuer in our EHR. Would this be required to understand statuses like not-done with a status reason? I am curious how others model this.

**Comment by masnick** [comment]
I agree with @jmandel above:

1. Keep `isSubpotent` MS, update `short` and `definition` to reflect that this SHALL be populated if the dose is subpotent and otherwise SHALL be null.
2. Remove MS from `subpotentReason` -- it's unlikely the information in this element will result in a Verifier accepting a subpotent dose.

I think we do need to keep `isSubpotent` in the profile rather than making it `0..0`, and Verifiers will need to support it. My concern is that if an Issuer does support the element, if we make it `0..0` they will mistakenly just strip out this element rather than the entire resource.

**Comment by torresdrew** [comment]
Will there be guidance on when a MS field is not populated for implementers that do not support that field? Vaccines are being administered in the field currently, and this documentation just doesn't exist for our EHR. Even if I were to get that field added it would be 18 months before it would be out in the field due to package and workflow deployments.

**Comment by masnick** [comment]
I believe our definition of MS for an Issuer should be "you must include it if it's in your system". If it's not in the system, then the Issuer is off the hook from a conformance perspective.

That doesn't mean that the Verifier will consider a VC valid if these data are missing -- I believe we are leaving it up to the Verifier whether the data in the VC are sufficient to consider the patient vaccinated. But if the data weren't collected in the first place, there's nothing we can do.

Specifically for `isSubpotent`, I think our IG should include:

> Verifiers SHALL assume that if an Immunization resource is provided and `isSubpotent` is not `true`, then the vaccination was not subpotent. Therefore, Issuers who do not store the data necessary to populate `isSubpotent` SHALL NOT produce an Immunization resource for a subpotent vaccination.

**Comment by Mturman3** [comment]
The above wording suggests to me that Issuers who do not capture this information, will be required to use this information as not to include an Immunization resource in the VC if it is subpotent.

**Comment by nkarip** [comment]
How about -

> Indication if a dose is considered to be subpotent. By default, a dose should be considered to be potent. Verifiers SHALL assume that if an Immunization resource is provided and isSubpotent is not true, then the dose was not subpotent. Issuers SHALL only populate isSubpotent if the value is true. Issuers SHALL NOT produce an Immunization resource for a known subpotent dose without populating isSubpotent.

**Comment by masnick** [comment]
That's great, thanks @nkarip!
