### ISSUE TITLE
protocolApplied backbone element should be optional

### ISSUE THREAD

**Issue by torresdrew** [dvci/vaccine-credential-ig#21]
As an EHR issuer, this data isn't supported currently. Initially, does it make sense to leverage a field that doesn't exist? I think it should be an optional backbone element and all children should be optional.

**Comment by masnick** [comment]
Another piece of information supporting making this optional or removing entirely:

Per discussion at a session of the public health FHIR working group last week, `protocolApplied` is meant to represent the **provider's intent**, not the whether the vaccination actually qualifies as the nth dose in a series.

The [ImmunizationEvaluation](https://www.hl7.org/fhir/immunizationevaluation.html) resource is meant to interpret an Immunization in the context of the patient's history and the vaccination schedule. Presumably `ImmunizationEvaluation.doseNumber` and `ImmunizationEvaluation.seriesDoses` would be authoritative.

Based on this, I think our options are:

1. Use `Immunization` and make the dose/series elements optional.
2. Switch to or also allow for `ImmunizationEvaluation` resources as part of the bundle.

I favor Option 1 as a starting point since the dose/series information isn't necessarily available in the EHR anyway, it's simpler, and it seems like we would want to leave the "evaluation" up to the party receiving the VC anyway. This would mean that separate `Immunization` resources would be required in the bundle for each dose of the COVID vaccine, rather than theoretically just including a single resource.

I'm open to profiling `ImmunizationEvaluation` as well, but I think we should make sure there is a solid use case justification before adding it.

**Comment by masnick** [comment]
Discussion moved to #10.
